# Site settings
title: Quest TIC
description: "A minimal blog template, build with Jekyll."
url: "https://juanlu-millan.github.io/QuestTIC/"
author:
  name: "Juan Luis Millán Hidalgo"
  email: ""
  url: "https://juanlu-millan.github.io/QuestTIC/#"

# Build settings
baseurl: /emerald/ # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
